cico:
  key: CICO#
cloudinary:
  apiKey: 236829668753326
  apiSecretKey: XDI2Rc8Ty0kDn1rGOiAAWqTG6VI
  cloudName: df04kiqy3
secret: abhi9462
server:
  port: 8080
spring: 
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:Amit@123}
#    url: jdbc:mysql://${MYSQL_HOST:108.181.203.244}:${MYSQL_PORT:3306}/fees_management?createDatabaseIfNotExist=true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/fees_management-1?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    hikari:
      maximum-pool-size: 20              # Increase if you're under heavy load
      minimum-idle: 5
      idle-timeout: 60000                # 1 minute
      max-lifetime: 300000               # 5 minutes (MySQL default is 8 hours; keep under that)
      keepalive-time: 30000              # Ping idle connections every 30 seconds
      connection-timeout: 10000          # Wait max 10s for a connection from pool
      validation-timeout: 3000           # Fail validation quickly (3s)
      leak-detection-threshold: 10000    # Log warning if connection not closed in 10s
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  credentials:
  username: root
  password: Amit@123
  
  kafka:
    consumer:
      bootstrap-servers: cico.dollopinfotech.com:9092
      key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer '
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: cico.dollopinfotech.com:9092
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer '
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: smtp.gmail.com
    password: xxoy tfgz xomq pxdv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: uraj47986@gmail.com
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  logging:
    level:
      com.zaxxer.hikari: DEBUG
      com.zaxxer.hikari.HikariConfig: DEBUG
      com.zaxxer.hikari.HikariDataSource: DEBUG
staticPath: \src\main\resources\static\
piston:
  api:
    url: https://emkc.org/api/v2/piston

#  data server ip :108.181.203.244



